### PR TITLE
Fixes behavior of `progress_messengers`

### PR DESCRIPTION
**Pull request by tomchor**
Closes https://github.com/tomchor/Oceanostics.jl/issues/71

Simple fix so that the `SingleLineProgressMessenger` is actually single line

### CODE REVIEW

**Review by navidcy — APPROVED** [review]

**Comment by glwagner** [comment]
Could make sense to test this

**Comment by tomchor** [comment]
> Could make sense to test this

Testing that the number of lines matches what we expect? I don't know of a simple way to write such a test...

**Comment by glwagner** [comment]
After some trial and error it looks the following will work. First create one file with

```julia
using Oceananigans
using Oceanostics

grid = RectilinearGrid(size=(4, 4, 4), extent=(1, 1, 1))
closure = ScalarDiffusivity(ν=1e-6, κ=1e-7)
buoyancy = Buoyancy(model=BuoyancyTracer())
coriolis = FPlane(1e-4)
model = NonhydrostaticModel(; grid, closure, buoyancy, coriolis, tracers=:b)

messenger = SingleLineProgressMessenger(initial_wall_time_seconds=1e-9 * time_ns())
simulation = Simulation(model; Δt=1e-2, stop_iteration=1)
messenger(simulation)
```

Then if this file is "`run_progress_messenger.jl`", the test looks something like

```julia
using Test
io = IOBuffer(append=true)
run(pipeline(`julia --project run_progress_messenger.jl`, stderr=io))
@test countlines(io) == 1
```

**Comment by tomchor** [comment]
> After some trial and error it looks the following will work. First create one file with
> 
> ```julia
> using Oceananigans
> using Oceanostics
> 
> grid = RectilinearGrid(size=(4, 4, 4), extent=(1, 1, 1))
> closure = ScalarDiffusivity(ν=1e-6, κ=1e-7)
> buoyancy = Buoyancy(model=BuoyancyTracer())
> coriolis = FPlane(1e-4)
> model = NonhydrostaticModel(; grid, closure, buoyancy, coriolis, tracers=:b)
> 
> messenger = SingleLineProgressMessenger(initial_wall_time_seconds=1e-9 * time_ns())
> simulation = Simulation(model; Δt=1e-2, stop_iteration=1)
> messenger(simulation)
> ```
> 
> Then if this file is "`run_progress_messenger.jl`", the test looks something like
> 
> ```julia
> using Test
> io = IOBuffer(append=true)
> run(pipeline(`julia --project run_progress_messenger.jl`, stderr=io))
> @test countlines(io) == 1
> ```
> 
> to test multiple closures, the closure could be an input argument to `run_progress_messenger.jl` OR you can just loop over `closures` within that file and then `@test countlines(io) === number_of_closure`. Or something.

Couldn't make this work. Apparently running commands from within Julia isn't super easy and isn't the same from environment to environment. I found many threads like[this one](https://discourse.julialang.org/t/fail-to-run-shell-command/55543).

For me, even running this gives me an error:

```julia
julia> run(pipeline(`julia`, stderr=io))
ERROR: IOError: could not spawn `julia`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(file::String, cmd::Cmd, stdio::Vector{Any})
   @ Base ./process.jl:99
 [2] #637
   @ ./process.jl:112 [inlined]
 [3] setup_stdios(f::Base.var"#637#638"{Cmd}, stdios::Vector{Any})
   @ Base ./process.jl:196
 [4] _spawn
   @ ./process.jl:111 [inlined]
 [5] _spawn(::Base.CmdRedirect, ::Vector{Any})
   @ Base ./process.jl:139
 [6] run(::Base.CmdRedirect; wait::Bool)
   @ Base ./process.jl:439
 [7] run(::Base.CmdRedirect)
   @ Base ./process.jl:438
 [8] top-level scope
   @ REPL[15]:1
```

I think I'm gonna merge this as it is right now and we can open a new PR once we come up with a different way to test this.

**Comment by glwagner** [comment]
> julia> run(pipeline(`julia`, stderr=io))
ERROR: IOError: could not spawn `julia`: no such file or directory (ENOENT)
Stacktrace:

You may need to run a script, eg `julia script.jl` rather than launch the REPL.

**Pull request merged**
