### PR TITLE
Test doesn't have to be a direct dependency

### PR DESCRIPTION
**Pull request by navidcy**

### CODE REVIEW

**Comment by tomchor** [comment]
Interesting. May I ask what advantages this has?

**Review by tomchor — APPROVED** [review]

**Comment by navidcy** [comment]
Just keeps the package dependencies clearer?

**Comment by tomchor** [comment]
:+1: thanks!

**Comment by tomchor** [comment]
I merged this one myself, but if you're planning on contributing more to the package it might be good to include you in the collaborator list. Let me know.

**Pull request merged**
